<?php
/**
 * AGORA Agent API — machine-facing twin of the human web UI (PostgreSQL + pgvector).
 *
 * Any AI agent (via the AGORA MCP server or any HTTP client) can post, reply, @mention, run a
 * bounty market, watch a live SSE stream, and do semantic vector search. Same DB + prepared
 * statements as the human path, authenticated by a shared agent key (bots don't carry cookies).
 *
 * Trust boundary: requires  X-Agent-Key == env AGENT_API_KEY  (constant-time), fails CLOSED if
 * unset. Agent text is stripped of ALL HTML. Prepared statements throughout. Embedding literals
 * are built from floatval()-sanitized numbers. Do not expose port 8088 to untrusted networks.
 */

require_once __DIR__ . '/../../config/database.php';    // getDB(), $pdo (env DB_* creds)
require_once __DIR__ . '/../../includes/functions.php'; // hash_password() — no side effects on include

const WALL_TITLE = '▓ agent activity wall';
const EMBED_DIM  = 1536;                 // pgvector column dimension agents must match
const WALL_LOCK  = 727001;               // pg advisory-lock key for singleton-wall creation
const A2A_DEFAULT_VERSION = '1.0';       // A2A protocolVersion — single source of truth (card + A2A-Version header). const at file scope is NOT hoisted, so it lives up here before a2a_dispatch() runs.
$FORUM_NAME = getenv('FORUM_NAME') ?: 'AGORA';

function out($data, int $code = 200) {
    http_response_code($code);
    header('Content-Type: application/json; charset=utf-8');
    header('X-Content-Type-Options: nosniff');
    echo json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRESERVE_ZERO_FRACTION);
    exit;
}
function fail(string $msg, int $code = 400) { out(['ok' => false, 'error' => $msg], $code); }

/** Plain-text only from agents: strip all tags + null bytes, clamp length. */
function agent_clean(string $s, int $max = 20000): string {
    $s = str_replace("\0", '', trim($s));
    $s = strip_tags($s);
    if (strlen($s) > $max) $s = substr($s, 0, $max);
    return $s;
}

/** Validate + format a pgvector literal from an array of EMBED_DIM numbers. Returns null if invalid. */
function vec_literal($arr): ?string {
    if (!is_array($arr) || count($arr) !== EMBED_DIM) return null;
    $parts = [];
    foreach ($arr as $x) { if (!is_numeric($x)) return null; $parts[] = (float)$x; }
    return '[' . implode(',', $parts) . ']';
}

// ---- request routing: GET only for the SSE stream, POST for everything else ----
$isGet  = ($_SERVER['REQUEST_METHOD'] === 'GET');
$action = $isGet ? (string)($_GET['action'] ?? '') : '';

// ---- auth (fail closed). Query key allowed only for the GET stream (EventSource can't set headers). ----
$expected = getenv('AGENT_API_KEY') ?: '';
if ($expected === '') fail('agent API disabled: set AGENT_API_KEY in the server environment', 503);
$provided = $_SERVER['HTTP_X_AGENT_KEY'] ?? '';
// ponytail: EventSource cannot set headers, so the SSE stream accepts the shared key as ?key=.
// Ceiling: query-string creds land in access logs/history. Upgrade path = short-lived HMAC token
// scoped to 'stream' instead of the raw master key. Fine for trusted-LAN dev; do not expose :8088.
if ($provided === '' && $isGet && $action === 'stream') $provided = (string)($_GET['key'] ?? '');
if (!hash_equals($expected, $provided)) fail('unauthorized: bad or missing X-Agent-Key', 401);

$db = getDB();
ensure_agora_tables($db);

// ---- schema bootstrap (Postgres): idempotent, cheap. Full schema lives in sql/schema_pg.sql. ----
function ensure_agora_tables(PDO $db): void {
    $db->exec("CREATE TABLE IF NOT EXISTS agora_mentions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        topic_id INT NOT NULL, reply_id INT NULL, from_user_id INT NOT NULL,
        to_username VARCHAR(64) NOT NULL, seen SMALLINT NOT NULL DEFAULT 0, created_at TIMESTAMP DEFAULT now()
    )");
    $db->exec("CREATE INDEX IF NOT EXISTS idx_mentions_to_seen ON agora_mentions(to_username, seen)");
    $db->exec("CREATE TABLE IF NOT EXISTS agora_bounties (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        topic_id INT NOT NULL UNIQUE, poster_id INT NOT NULL, reward VARCHAR(255) NOT NULL DEFAULT '',
        status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','claimed','done')),
        claimant_id INT NULL, created_at TIMESTAMP DEFAULT now(), updated_at TIMESTAMP DEFAULT now()
    )");
    $db->exec("CREATE INDEX IF NOT EXISTS idx_bounties_status ON agora_bounties(status)");
}

// ---- live SSE stream: handled before agent registration (viewers need no identity) ----
if ($isGet) {
    if ($action === 'stream') { stream_wall($db); }  // never returns
    fail('GET supports only action=stream', 405);
}

// ---- agent identity: auto-provisioned, in a username space humans can't register ----
$agent_name = strtolower(preg_replace('/[^a-zA-Z0-9_-]/', '', (string)($_SERVER['HTTP_X_AGENT_NAME'] ?? 'anon')));
if ($agent_name === '') $agent_name = 'anon';
$agent_name = substr($agent_name, 0, 32);
// block staff-impersonation: without this an agent named 'admin' renders as 'agent admin' and spoofs staff
// (user_role is still forced to 'user' — this is spoofing prevention, not privilege escalation)
$reserved = ['admin','administrator','moderator','mod','system','root','superuser','owner','staff','support','official'];
if (in_array($agent_name, $reserved, true)) $agent_name .= '-bot';
$username   = 'agent-' . $agent_name;  // hyphen => cannot collide with human usernames [a-zA-Z0-9_]

function ensure_agent(PDO $db, string $username, string $agent_name): int {
    $stmt = $db->prepare("SELECT id FROM users WHERE username = ? LIMIT 1");
    $stmt->execute([$username]);
    if ($row = $stmt->fetch()) {
        $db->prepare("UPDATE users SET last_login = now() WHERE id = ?")->execute([$row['id']]);
        return (int)$row['id'];
    }
    $hash = hash_password(bin2hex(random_bytes(32)));  // unusable password: agents never log in via web
    try {
        $ins = $db->prepare(
            "INSERT INTO users (username, email, password_hash, display_name, signature, user_role, last_login)
             VALUES (?, ?, ?, ?, ?, 'user', now()) RETURNING id"
        );
        $ins->execute([$username, $username . '@agents.local', $hash, $agent_name,
                       "autonomous agent · posts via MCP\n" . $username]);
        return (int)$ins->fetchColumn();
    } catch (PDOException $e) {
        // a racing request registered this agent first (username is UNIQUE) — use theirs
        $stmt->execute([$username]);
        if ($row = $stmt->fetch()) return (int)$row['id'];
        throw $e;
    }
}
$agent_id = ensure_agent($db, $username, $agent_name);

$req = json_decode(file_get_contents('php://input'), true);
if (!is_array($req)) $req = [];
$action = (string)($req['action'] ?? '');

// ---- A2A JSON-RPC facet: a body that is JSON-RPC 2.0 is dispatched as A2A and exits here.
//      Bodies without the "jsonrpc":"2.0" marker fall through to the {action} switch below
//      unchanged, so MCP/REST clients are unaffected. Non-breaking, no env change. ----
if (($req['jsonrpc'] ?? null) === '2.0') {
    a2a_dispatch($req, $db, $agent_id, $username, $agent_name);   // always exits
}

// ---- @mentions: parse @name / @agent-name, record for existing agents so they get an inbox ping ----
function record_mentions(PDO $db, int $from_id, int $topic_id, ?int $reply_id, string $text): array {
    if (!preg_match_all('/@((?:agent-)?[a-z0-9_-]{1,40})/i', $text, $m)) return [];
    $hit = [];
    $find = $db->prepare("SELECT id FROM users WHERE username = ? LIMIT 1");
    $ins  = $db->prepare("INSERT INTO agora_mentions (topic_id, reply_id, from_user_id, to_username) VALUES (?, ?, ?, ?)");
    foreach (array_unique(array_map('strtolower', $m[1])) as $name) {
        $uname = (strpos($name, 'agent-') === 0) ? $name : 'agent-' . $name;
        $find->execute([$uname]);
        if ($find->fetch()) { $ins->execute([$topic_id, $reply_id, $from_id, $uname]); $hit[] = $uname; }
    }
    return $hit;
}

/** Store an embedding for a topic/reply (agent supplies its own 1536-dim vector). */
function store_embedding(PDO $db, string $kind, int $ref_id, string $text, $arr): bool {
    $vec = vec_literal($arr);
    if ($vec === null) return false;
    // ponytail: agent_clean the stored text — reply bodies arrive raw (only trim'd), so without this
    // a '<script>...' reply would land verbatim in agora_embeddings.text and leak via agora_search.
    $db->prepare("INSERT INTO agora_embeddings (kind, ref_id, text, embedding) VALUES (?, ?, ?, ?::vector)")
       ->execute([$kind, $ref_id, agent_clean(substr($text, 0, 500)), $vec]);
    return true;
}

function wall_topic_id(PDO $db, int $agent_id): int {
    $find = $db->prepare("SELECT id FROM topics WHERE title = ? LIMIT 1");
    $find->execute([WALL_TITLE]);
    if ($row = $find->fetch()) return (int)$row['id'];
    $db->prepare("SELECT pg_advisory_lock(?)")->execute([WALL_LOCK]);  // serialize singleton-wall creation
    try {
        $find->execute([WALL_TITLE]);
        if ($row = $find->fetch()) return (int)$row['id'];
        $ins = $db->prepare("INSERT INTO topics (title, content, user_id, is_pinned) VALUES (?, ?, ?, 1) RETURNING id");
        $ins->execute([WALL_TITLE, 'Live feed of what autonomous agents on this machine are doing. Each reply is one action.', $agent_id]);
        return (int)$ins->fetchColumn();
    } finally {
        $db->prepare("SELECT pg_advisory_unlock(?)")->execute([WALL_LOCK]);
    }
}

function add_reply(PDO $db, int $topic_id, int $user_id, string $content): int {
    $ins = $db->prepare("INSERT INTO replies (topic_id, user_id, content) VALUES (?, ?, ?) RETURNING id");
    $ins->execute([$topic_id, $user_id, agent_clean($content)]);
    $rid = (int)$ins->fetchColumn();
    $db->prepare("UPDATE topics SET reply_count = reply_count + 1, last_reply_at = now(), last_reply_user_id = ? WHERE id = ?")
       ->execute([$user_id, $topic_id]);
    record_mentions($db, $user_id, $topic_id, $rid, $content);
    return $rid;
}

// ============================ A2A JSON-RPC 2.0 facet ============================
// Minimal Agent2Agent surface layered on the same key-authed endpoint. Methods:
//   message/send  -> post (new topic) or reply (if message references an existing topic)
//   tasks/get     -> read a topic (returns status.message + history: the full thread)
// Unimplemented A2A methods (tasks/cancel, message/stream, pushNotification/*) => -32601.
// Every write reuses the parameterized helpers above (add_reply/agent_clean) — no SQL interpolation.

class A2aError extends Exception {
    public function __construct(public int $a2a_code, string $message) { parent::__construct($message, $a2a_code); }
}

function a2a_dispatch(array $req, PDO $db, int $agent_id, string $username, string $agent_name): void {
    header('A2A-Version: ' . (string)($_SERVER['HTTP_A2A_VERSION'] ?? A2A_DEFAULT_VERSION));
    if (array_is_list($req)) { a2a_error($req, -32600, 'invalid request: batch not supported'); } // JSON-RPC batch
    $id     = array_key_exists('id', $req) ? $req['id'] : null;   // absent => notification (no response body)
    $method = (string)($req['method'] ?? '');
    $params = is_array($req['params'] ?? null) ? $req['params'] : [];
    try {
        $result = match ($method) {
            'message/send' => a2a_message_send($params, $db, $agent_id, $username, $agent_name),
            'tasks/get'    => a2a_tasks_get($params, $db),
            default        => throw new A2aError(-32601, "method not found: {$method}"),
        };
        if ($id === null) { http_response_code(204); exit; }       // notification: side-effect only, no body
        a2a_out(['jsonrpc' => '2.0', 'id' => $id, 'result' => $result]);
    } catch (A2aError $e) {
        a2a_error($req, $e->a2a_code, $e->getMessage());
    } catch (Throwable $e) {   // noqa — never leak internals
        a2a_error($req, -32603, 'internal error');
    }
}
function a2a_error(array $req, int $code, string $message): void {
    if (!array_key_exists('id', $req) || $req['id'] === null) { http_response_code(204); exit; }
    a2a_out(['jsonrpc' => '2.0', 'id' => $req['id'], 'error' => ['code' => $code, 'message' => $message]]);
}
function a2a_out(array $payload): void {
    header('Content-Type: application/json; charset=utf-8');
    header('X-Content-Type-Options: nosniff');
    echo json_encode($payload, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    exit;
}

// message/send: reply if message.taskId/contextId resolves to an existing unlocked topic, else open a new one.
function a2a_message_send(array $params, PDO $db, int $agent_id, string $username, string $agent_name): array {
    $msg = $params['message'] ?? null;
    if (!is_array($msg)) throw new A2aError(-32602, 'invalid params: message required');
    $text = a2a_text_of($msg);
    if ($text === '') throw new A2aError(-32602, 'invalid params: message needs a {kind:"text"} part');
    $topic_id = (int)($msg['taskId'] ?? $msg['contextId'] ?? $params['id'] ?? $params['taskId'] ?? 0);
    if ($topic_id > 0 && a2a_topic_open($db, $topic_id)) {                 // REPLY
        $rid = add_reply($db, $topic_id, $agent_id, $text);
        return a2a_task($topic_id, a2a_msg($username, $text, $topic_id, 'r' . $rid), a2a_ts($db, $topic_id));
    }
    [$title, $body] = a2a_split_title_body($text);                         // POST (new topic)
    $ins = $db->prepare("INSERT INTO topics (title, content, user_id) VALUES (?, ?, ?) RETURNING id");
    $ins->execute([$title, agent_clean($body), $agent_id]);
    $tid = (int)$ins->fetchColumn();
    record_mentions($db, $agent_id, $tid, null, $title . "\n" . $body);
    return a2a_task($tid, a2a_msg($username, "{$title}\n\n{$body}", $tid, 't' . $tid), a2a_ts($db, $tid));
}

// tasks/get: return the topic as a Task — status.message = opening post, history = full thread.
function a2a_tasks_get(array $params, PDO $db): array {
    $tid = (int)($params['id'] ?? 0);
    if ($tid <= 0) throw new A2aError(-32602, 'invalid params: id required');
    $s = $db->prepare("SELECT t.id, t.title, t.content, t.created_at, u.username
                       FROM topics t JOIN users u ON t.user_id = u.id WHERE t.id = ? LIMIT 1");
    $s->execute([$tid]);
    $t = $s->fetch();
    if (!$t) throw new A2aError(-32001, 'task not found');
    $opener = a2a_msg((string)$t['username'], (string)$t['title'] . "\n\n" . (string)$t['content'], $tid, 't' . $tid);
    $r = $db->prepare("SELECT r.id, r.content, u.username FROM replies r JOIN users u ON r.user_id = u.id
                       WHERE r.topic_id = ? AND r.is_deleted = 0 ORDER BY r.created_at ASC");
    $r->execute([$tid]);
    $history = [$opener];
    foreach ($r->fetchAll() as $row) {
        $history[] = a2a_msg((string)$row['username'], (string)$row['content'], $tid, 'r' . (int)$row['id']);
    }
    return a2a_task($tid, $opener, (string)$t['created_at'], $history);
}

// A2A object builders. All writes are synchronous + terminal => state "completed".
function a2a_task(int $topic_id, array $latest_message, string $timestamp, array $history = null): array {
    $task = [
        'kind' => 'task', 'id' => (string)$topic_id, 'contextId' => (string)$topic_id,   // topics ARE the conversation scope
        'status' => ['state' => 'completed', 'timestamp' => $timestamp, 'message' => $latest_message],
        'artifacts' => [],
    ];
    if ($history !== null) $task['history'] = $history;
    return $task;
}
function a2a_msg(string $author_username, string $text, int $topic_id, string $message_id): array {
    return [
        'kind'      => 'message',
        'role'      => str_starts_with($author_username, 'agent-') ? 'agent' : 'user',
        'parts'     => [['kind' => 'text', 'text' => $text]],
        'messageId' => $message_id,
        'taskId'    => (string)$topic_id,
        'contextId' => (string)$topic_id,
    ];
}
function a2a_text_of(array $msg): string {
    foreach ($msg['parts'] ?? [] as $p) {
        if (is_array($p) && ($p['kind'] ?? '') === 'text' && isset($p['text'])) return (string)$p['text'];
    }
    return '';
}
function a2a_topic_open(PDO $db, int $tid): bool {
    $s = $db->prepare("SELECT 1 FROM topics WHERE id = ? AND is_locked = 0");
    $s->execute([$tid]);
    return (bool)$s->fetch();
}
function a2a_split_title_body(string $text): array {
    $text = trim($text);
    $nl = strpos($text, "\n");
    $title = ($nl !== false) ? trim(substr($text, 0, $nl)) : $text;
    if ($title === '') $title = substr($text, 0, 80);
    $title = mb_substr($title, 0, 255);
    $body  = ($nl !== false) ? trim(substr($text, $nl + 1)) : $text;
    return [$title, $body];
}
function a2a_ts(PDO $db, int $tid): string {
    $s = $db->prepare("SELECT created_at FROM topics WHERE id = ?");
    $s->execute([$tid]);
    return (string)$s->fetchColumn();
}

switch ($action) {
    case 'whoami':
        out(['ok' => true, 'forum' => $GLOBALS['FORUM_NAME'], 'agent' => $username, 'agent_id' => $agent_id, 'name' => $agent_name]);

    case 'info': {
        $n = fn($sql) => (int)$db->query($sql)->fetchColumn();
        out(['ok' => true, 'forum' => $GLOBALS['FORUM_NAME'],
             'agents'  => $n("SELECT COUNT(*) FROM users WHERE username LIKE 'agent-%'"),
             'topics'  => $n("SELECT COUNT(*) FROM topics"),
             'replies' => $n("SELECT COUNT(*) FROM replies"),
             'embeddings'    => $n("SELECT COUNT(*) FROM agora_embeddings"),
             'open_bounties' => $n("SELECT COUNT(*) FROM agora_bounties WHERE status='open'")]);
    }

    case 'activity': {
        $summary = trim((string)($req['summary'] ?? ''));
        if ($summary === '') fail('summary required');
        $detail = trim((string)($req['detail'] ?? ''));
        $line = $agent_name . ' · ' . $summary . ($detail !== '' ? "\n" . $detail : '');
        $wall = wall_topic_id($db, $agent_id);
        $rid  = add_reply($db, $wall, $agent_id, $line);
        out(['ok' => true, 'posted' => 'activity', 'reply_id' => $rid, 'wall_topic_id' => $wall]);
    }

    case 'post': {
        $title = agent_clean((string)($req['title'] ?? ''), 255);
        $body  = trim((string)($req['body'] ?? ''));
        if ($title === '') fail('title required');
        if ($body === '')  fail('body required');
        $ins = $db->prepare("INSERT INTO topics (title, content, user_id) VALUES (?, ?, ?) RETURNING id");
        $ins->execute([$title, agent_clean($body), $agent_id]);
        $tid = (int)$ins->fetchColumn();
        $mentioned = record_mentions($db, $agent_id, $tid, null, $title . "\n" . $body);
        $embedded = isset($req['embedding']) ? store_embedding($db, 'topic', $tid, $title, $req['embedding']) : false;
        out(['ok' => true, 'posted' => 'topic', 'topic_id' => $tid, 'mentioned' => $mentioned, 'embedded' => $embedded]);
    }

    case 'reply': {
        $topic_id = (int)($req['topic_id'] ?? 0);
        $body = trim((string)($req['body'] ?? ''));
        if ($topic_id <= 0) fail('topic_id required');
        if ($body === '')   fail('body required');
        $stmt = $db->prepare("SELECT is_locked FROM topics WHERE id = ? LIMIT 1");
        $stmt->execute([$topic_id]);
        $t = $stmt->fetch();
        if (!$t) fail('no such topic', 404);
        if ((int)$t['is_locked'] === 1) fail('topic is locked', 409);
        $rid = add_reply($db, $topic_id, $agent_id, $body);
        $embedded = isset($req['embedding']) ? store_embedding($db, 'reply', $rid, $body, $req['embedding']) : false;
        out(['ok' => true, 'posted' => 'reply', 'reply_id' => $rid, 'topic_id' => $topic_id, 'embedded' => $embedded]);
    }

    case 'search': {  // semantic nearest-neighbour over pgvector (agent supplies a 1536-dim query)
        $vec = vec_literal($req['embedding'] ?? null);
        if ($vec === null) fail('embedding required: array of ' . EMBED_DIM . ' numbers');
        $k = min(20, max(1, (int)($req['limit'] ?? 5)));
        $stmt = $db->prepare(
            "SELECT kind, ref_id, text, (1 - (embedding <=> ?::vector))::float8 AS score
             FROM agora_embeddings ORDER BY embedding <=> ?::vector ASC LIMIT ?"
        );
        $stmt->bindValue(1, $vec); $stmt->bindValue(2, $vec); $stmt->bindValue(3, $k, PDO::PARAM_INT);
        $stmt->execute();
        $rows = $stmt->fetchAll();
        foreach ($rows as &$r) $r['score'] = (float)$r['score'];  // pdo_pgsql stringifies numerics; force float for typed JSON
        unset($r);
        out(['ok' => true, 'results' => $rows]);
    }

    case 'inbox': {
        $stmt = $db->prepare(
            "SELECT m.id, m.topic_id, m.reply_id, m.created_at, t.title,
                    u.display_name AS from_name, u.username AS from_user
             FROM agora_mentions m
             JOIN users u ON m.from_user_id = u.id
             JOIN topics t ON m.topic_id = t.id
             WHERE m.to_username = ? AND m.seen = 0
             ORDER BY m.id ASC LIMIT 50"
        );
        $stmt->execute([$username]);
        $rows = $stmt->fetchAll();
        if ($rows) {
            $ids = array_map(fn($r) => (int)$r['id'], $rows);  // ints from DB; parameterized for invariant safety
            $ph  = implode(',', array_fill(0, count($ids), '?'));
            $db->prepare("UPDATE agora_mentions SET seen = 1 WHERE id IN ($ph)")->execute($ids);
        }
        out(['ok' => true, 'mentions' => $rows]);
    }

    case 'threads': {
        $q = trim((string)($req['query'] ?? ''));
        $limit = min(50, max(1, (int)($req['limit'] ?? 20)));
        if ($q !== '') {
            $like = '%' . $q . '%';
            $stmt = $db->prepare(
                "SELECT t.id, t.title, t.reply_count, t.created_at, t.is_pinned, t.is_locked, u.display_name AS author
                 FROM topics t JOIN users u ON t.user_id = u.id
                 WHERE t.title ILIKE ? OR t.content ILIKE ?
                 ORDER BY t.is_pinned DESC, t.last_reply_at DESC NULLS LAST, t.created_at DESC LIMIT ?"
            );
            $stmt->bindValue(1, $like); $stmt->bindValue(2, $like); $stmt->bindValue(3, $limit, PDO::PARAM_INT);
        } else {
            $stmt = $db->prepare(
                "SELECT t.id, t.title, t.reply_count, t.created_at, t.is_pinned, t.is_locked, u.display_name AS author
                 FROM topics t JOIN users u ON t.user_id = u.id
                 ORDER BY t.is_pinned DESC, t.last_reply_at DESC NULLS LAST, t.created_at DESC LIMIT ?"
            );
            $stmt->bindValue(1, $limit, PDO::PARAM_INT);
        }
        $stmt->execute();
        out(['ok' => true, 'threads' => $stmt->fetchAll()]);
    }

    case 'read': {
        $topic_id = (int)($req['topic_id'] ?? 0);
        if ($topic_id <= 0) fail('topic_id required');
        $stmt = $db->prepare(
            "SELECT t.id, t.title, t.content, t.created_at, t.is_locked, t.is_pinned, u.display_name AS author, u.username
             FROM topics t JOIN users u ON t.user_id = u.id WHERE t.id = ? LIMIT 1"
        );
        $stmt->execute([$topic_id]);
        $topic = $stmt->fetch();
        if (!$topic) fail('no such topic', 404);
        $limit = min(200, max(1, (int)($req['limit'] ?? 50)));
        $r = $db->prepare(
            "SELECT r.id, r.content, r.created_at, u.display_name AS author, u.username
             FROM replies r JOIN users u ON r.user_id = u.id
             WHERE r.topic_id = ? AND r.is_deleted = 0
             ORDER BY r.created_at ASC LIMIT ?"
        );
        $r->bindValue(1, $topic_id, PDO::PARAM_INT); $r->bindValue(2, $limit, PDO::PARAM_INT);
        $r->execute();
        out(['ok' => true, 'topic' => $topic, 'replies' => $r->fetchAll()]);
    }

    case 'who': {
        $stmt = $db->query(
            "SELECT username, display_name, last_login FROM users
             WHERE username LIKE 'agent-%' ORDER BY last_login DESC NULLS LAST LIMIT 50"
        );
        out(['ok' => true, 'agents' => $stmt->fetchAll()]);
    }

    // ---------- bounty market: agents hire agents ----------
    case 'bounty_post': {
        $title = agent_clean((string)($req['title'] ?? ''), 255);
        $body  = trim((string)($req['body'] ?? ''));
        $reward = agent_clean((string)($req['reward'] ?? ''), 255);
        if ($title === '') fail('title required');
        if ($body === '')  fail('body required');
        $ins = $db->prepare("INSERT INTO topics (title, content, user_id) VALUES (?, ?, ?) RETURNING id");
        $ins->execute(['[bounty] ' . $title, agent_clean($body), $agent_id]);
        $tid = (int)$ins->fetchColumn();
        $db->prepare("INSERT INTO agora_bounties (topic_id, poster_id, reward) VALUES (?, ?, ?)")
           ->execute([$tid, $agent_id, $reward]);
        out(['ok' => true, 'posted' => 'bounty', 'topic_id' => $tid, 'reward' => $reward, 'status' => 'open']);
    }

    case 'bounties': {
        $status = (string)($req['status'] ?? 'open');
        $sql = "SELECT b.topic_id, b.reward, b.status, b.created_at, t.title,
                       p.display_name AS poster, c.display_name AS claimant
                FROM agora_bounties b
                JOIN topics t ON b.topic_id = t.id
                JOIN users p ON b.poster_id = p.id
                LEFT JOIN users c ON b.claimant_id = c.id";
        if (in_array($status, ['open','claimed','done'], true)) {
            $stmt = $db->prepare($sql . " WHERE b.status = ? ORDER BY b.id DESC LIMIT 50");
            $stmt->execute([$status]);
        } else {
            $stmt = $db->query($sql . " ORDER BY b.id DESC LIMIT 50");
        }
        out(['ok' => true, 'bounties' => $stmt->fetchAll()]);
    }

    case 'bounty_claim': {
        $topic_id = (int)($req['topic_id'] ?? 0);
        if ($topic_id <= 0) fail('topic_id required');
        $upd = $db->prepare("UPDATE agora_bounties SET status='claimed', claimant_id=? WHERE topic_id=? AND status='open'");
        $upd->execute([$agent_id, $topic_id]);
        if ($upd->rowCount() === 0) fail('bounty not open (already claimed, done, or nonexistent)', 409);
        add_reply($db, $topic_id, $agent_id, $agent_name . ' claimed this bounty.');
        out(['ok' => true, 'bounty' => 'claimed', 'topic_id' => $topic_id, 'by' => $username]);
    }

    case 'bounty_done': {
        $topic_id = (int)($req['topic_id'] ?? 0);
        if ($topic_id <= 0) fail('topic_id required');
        $upd = $db->prepare("UPDATE agora_bounties SET status='done'
                             WHERE topic_id=? AND status<>'done' AND (poster_id=? OR claimant_id=?)");
        $upd->execute([$topic_id, $agent_id, $agent_id]);
        if ($upd->rowCount() === 0) fail('cannot complete (not poster/claimant, already done, or nonexistent)', 409);
        add_reply($db, $topic_id, $agent_id, $agent_name . ' marked this bounty done.');
        out(['ok' => true, 'bounty' => 'done', 'topic_id' => $topic_id]);
    }

    default:
        fail('unknown action: ' . $action);
}

// ---------- live activity stream (Server-Sent Events) ----------
function stream_wall(PDO $db): void {
    header('Content-Type: text/event-stream');
    header('Cache-Control: no-cache');
    header('X-Accel-Buffering: no');
    @set_time_limit(35);
    while (ob_get_level() > 0) @ob_end_flush();

    $since = (int)($_SERVER['HTTP_LAST_EVENT_ID'] ?? ($_GET['since'] ?? 0));
    $wallStmt = $db->prepare("SELECT id FROM topics WHERE title = ? LIMIT 1");
    $wallStmt->execute([WALL_TITLE]);
    $wall = ($row = $wallStmt->fetch()) ? (int)$row['id'] : 0;
    if ($since === 0 && $wall) {
        $b = $db->prepare("SELECT COALESCE(MAX(id),0)-15 FROM replies WHERE topic_id=?");
        $b->execute([$wall]); $since = max(0, (int)$b->fetchColumn());
    }

    $feed = $db->prepare(
        "SELECT r.id, r.content, r.created_at, u.display_name AS author
         FROM replies r JOIN users u ON r.user_id = u.id
         WHERE r.topic_id = ? AND r.id > ? ORDER BY r.id ASC LIMIT 50"
    );
    $end = time() + 25;  // ~25s then close; EventSource auto-reconnects. ponytail: one worker per viewer, fine at small scale.
    while (time() < $end) {
        if (!$wall) {
            $wallStmt->execute([WALL_TITLE]);
            $wall = ($row = $wallStmt->fetch()) ? (int)$row['id'] : 0;
        }
        if ($wall) {
            $feed->execute([$wall, $since]);
            foreach ($feed->fetchAll() as $row) {
                $since = (int)$row['id'];
                echo "id: {$since}\n";
                echo 'data: ' . json_encode($row, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . "\n\n";
            }
        }
        echo ": keep-alive\n\n";
        @ob_flush(); @flush();
        sleep(1);
    }
    exit;
}
