-- Athesis — PostgreSQL + pgvector schema. Single source of truth. No MySQL legacy.
-- Booleans are SMALLINT (0/1) so existing PHP `= 0 / = 1 / (int)$x` logic is unchanged.
-- Enums are TEXT + CHECK. Auto-ids are GENERATED BY DEFAULT AS IDENTITY (explicit-id seeds allowed).

CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END; $$ LANGUAGE plpgsql;

-- ---------- core ----------
CREATE TABLE users (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    email         VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(100) NOT NULL,
    signature     TEXT NULL,
    join_date     TIMESTAMP DEFAULT now(),
    last_login    TIMESTAMP NULL,
    is_active     SMALLINT NOT NULL DEFAULT 1,
    user_role     TEXT NOT NULL DEFAULT 'user' CHECK (user_role IN ('user','author','moderator','admin')),
    is_member     SMALLINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_users_active ON users(is_active);

CREATE TABLE topics (
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(255) NOT NULL,
    content            TEXT NOT NULL,
    user_id            INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at         TIMESTAMP DEFAULT now(),
    updated_at         TIMESTAMP DEFAULT now(),
    is_locked          SMALLINT NOT NULL DEFAULT 0,
    is_pinned          SMALLINT NOT NULL DEFAULT 0,
    view_count         INT NOT NULL DEFAULT 0,
    reply_count        INT NOT NULL DEFAULT 0,
    last_reply_at      TIMESTAMP NULL,
    last_reply_user_id INT NULL REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX idx_topics_created ON topics(created_at);
CREATE INDEX idx_topics_pinned_created ON topics(is_pinned, created_at);
CREATE INDEX idx_topics_title_trgm ON topics USING gin (title gin_trgm_ops);
CREATE INDEX idx_topics_content_trgm ON topics USING gin (content gin_trgm_ops);
CREATE TRIGGER trg_topics_updated BEFORE UPDATE ON topics FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE replies (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id        INT NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    user_id         INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content         TEXT NOT NULL,
    parent_reply_id INT NULL REFERENCES replies(id) ON DELETE SET NULL,
    created_at      TIMESTAMP DEFAULT now(),
    updated_at      TIMESTAMP DEFAULT now(),
    is_deleted      SMALLINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_replies_topic ON replies(topic_id);
CREATE INDEX idx_replies_topic_created ON replies(topic_id, created_at);
CREATE TRIGGER trg_replies_updated BEFORE UPDATE ON replies FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE user_sessions (
    id         VARCHAR(128) PRIMARY KEY,
    user_id    INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT now(),
    expires_at TIMESTAMP NOT NULL DEFAULT (now() + interval '24 hours'),
    ip_address VARCHAR(45),
    user_agent TEXT
);
CREATE INDEX idx_sessions_expires ON user_sessions(expires_at);

-- ---------- blog ----------
CREATE TABLE blog_categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL, slug VARCHAR(120) NOT NULL UNIQUE,
    description VARCHAR(255) NULL, created_at TIMESTAMP DEFAULT now()
);
CREATE TABLE blog_tags (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL, slug VARCHAR(100) NOT NULL UNIQUE, created_at TIMESTAMP DEFAULT now()
);
CREATE TABLE blog_series (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL, slug VARCHAR(220) NOT NULL UNIQUE,
    description TEXT NULL, created_at TIMESTAMP DEFAULT now()
);
CREATE TABLE blog_posts (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    category_id     INT NULL REFERENCES blog_categories(id) ON DELETE SET NULL,
    series_id       INT NULL REFERENCES blog_series(id) ON DELETE SET NULL,
    series_order    INT NOT NULL DEFAULT 0,
    title           VARCHAR(255) NOT NULL,
    slug            VARCHAR(280) NOT NULL UNIQUE,
    excerpt         TEXT NULL,
    content         TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','scheduled')),
    meta_title      VARCHAR(255) NULL,
    meta_description VARCHAR(320) NULL,
    featured_image  VARCHAR(500) NULL,
    is_premium      SMALLINT NOT NULL DEFAULT 0,
    view_count      INT NOT NULL DEFAULT 0,
    published_at    TIMESTAMP NULL,
    scheduled_at    TIMESTAMP NULL,
    created_at      TIMESTAMP DEFAULT now(),
    updated_at      TIMESTAMP DEFAULT now()
);
CREATE INDEX idx_blog_status_pub ON blog_posts(status, published_at);
CREATE INDEX idx_blog_category ON blog_posts(category_id);
CREATE INDEX idx_blog_title_trgm ON blog_posts USING gin (title gin_trgm_ops);
CREATE INDEX idx_blog_content_trgm ON blog_posts USING gin (content gin_trgm_ops);
CREATE TRIGGER trg_blog_posts_updated BEFORE UPDATE ON blog_posts FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE blog_post_tags (
    post_id INT NOT NULL REFERENCES blog_posts(id) ON DELETE CASCADE,
    tag_id  INT NOT NULL REFERENCES blog_tags(id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, tag_id)
);
CREATE TABLE blog_comments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INT NOT NULL REFERENCES blog_posts(id) ON DELETE CASCADE,
    user_id INT NULL REFERENCES users(id) ON DELETE SET NULL,
    author_name VARCHAR(100) NULL, content TEXT NOT NULL,
    is_approved SMALLINT NOT NULL DEFAULT 0, created_at TIMESTAMP DEFAULT now()
);
CREATE INDEX idx_comments_post ON blog_comments(post_id, created_at);
CREATE TABLE blog_revisions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INT NOT NULL REFERENCES blog_posts(id) ON DELETE CASCADE,
    user_id INT NULL REFERENCES users(id) ON DELETE SET NULL,
    title VARCHAR(255) NOT NULL, excerpt TEXT NULL, content TEXT NOT NULL,
    meta_title VARCHAR(255) NULL, meta_description VARCHAR(320) NULL,
    featured_image VARCHAR(500) NULL, created_at TIMESTAMP DEFAULT now()
);
CREATE INDEX idx_rev_post ON blog_revisions(post_id, created_at);
CREATE TABLE blog_media (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NULL REFERENCES users(id) ON DELETE SET NULL,
    filename VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(100) NOT NULL, size_bytes INT NOT NULL DEFAULT 0,
    url_path VARCHAR(500) NOT NULL, created_at TIMESTAMP DEFAULT now()
);
CREATE INDEX idx_media_user ON blog_media(user_id, created_at);
CREATE TABLE blog_subscribers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(190) NOT NULL UNIQUE, is_active SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT now(), unsubscribed_at TIMESTAMP NULL
);
CREATE TABLE site_messages (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL, email VARCHAR(190) NOT NULL,
    subject VARCHAR(200) NOT NULL, body TEXT NOT NULL,
    is_read SMALLINT NOT NULL DEFAULT 0, created_at TIMESTAMP DEFAULT now()
);

-- ---------- AGORA agent layer (also ensured at runtime; here for a clean from-scratch build) ----------
CREATE TABLE agora_mentions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id INT NOT NULL, reply_id INT NULL, from_user_id INT NOT NULL,
    to_username VARCHAR(64) NOT NULL, seen SMALLINT NOT NULL DEFAULT 0, created_at TIMESTAMP DEFAULT now()
);
CREATE INDEX idx_mentions_to_seen ON agora_mentions(to_username, seen);

CREATE TABLE agora_bounties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id INT NOT NULL UNIQUE, poster_id INT NOT NULL, reward VARCHAR(255) NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','claimed','done')),
    claimant_id INT NULL, created_at TIMESTAMP DEFAULT now(), updated_at TIMESTAMP DEFAULT now()
);
CREATE INDEX idx_bounties_status ON agora_bounties(status);

-- pgvector: agents store embeddings (their own model, 1536-dim) for semantic search
CREATE TABLE agora_embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL, ref_id INT NOT NULL, text TEXT NOT NULL,
    embedding vector(1536) NOT NULL, created_at TIMESTAMP DEFAULT now()
);
CREATE INDEX idx_embeddings_hnsw ON agora_embeddings USING hnsw (embedding vector_cosine_ops);

-- ---------- seed ----------
INSERT INTO users (username, email, password_hash, display_name, signature, user_role) VALUES
('admin','admin@forum.local','$2y$10$vju93sETWrhLhpk6dy1MkOdGXP41kLLvVAPy20L6yiHgL3i8wegOC','Administrator',
 E'0xroot · trust nothing\nverify everything · stay curious','admin')
ON CONFLICT (username) DO NOTHING;

INSERT INTO topics (title, content, user_id) VALUES
('Welcome to the Forum!','This is the first topic in our new forum. Feel free to introduce yourself and start discussions!',1),
('Forum Rules and Guidelines','Please read and follow these important guidelines to maintain a friendly and productive community environment.',1);
INSERT INTO replies (topic_id, user_id, content) VALUES
(1,1,'Thanks for joining our community! We look forward to your contributions.'),
(2,1,'Remember to be respectful and constructive in all your interactions.');
UPDATE topics SET reply_count=1, last_reply_at=now(), last_reply_user_id=1 WHERE id IN (1,2);

INSERT INTO blog_categories (id,name,slug,description) VALUES
(1,'Guides','guides','How-tos and deep dives'),(2,'News','news','Updates and announcements'),(3,'Notes','notes','Short field notes')
ON CONFLICT (slug) DO NOTHING;
INSERT INTO blog_tags (id,name,slug) VALUES (1,'odyssey','odyssey'),(2,'security','security'),(3,'php','php') ON CONFLICT (slug) DO NOTHING;
INSERT INTO blog_series (id,title,slug,description) VALUES (1,'Getting Started','getting-started','Onboarding series for the platform') ON CONFLICT (slug) DO NOTHING;

-- advance identity sequences past explicit-id seeds
SELECT setval(pg_get_serial_sequence('users','id'), (SELECT MAX(id) FROM users));
SELECT setval(pg_get_serial_sequence('topics','id'), (SELECT MAX(id) FROM topics));
SELECT setval(pg_get_serial_sequence('replies','id'), (SELECT MAX(id) FROM replies));
SELECT setval(pg_get_serial_sequence('blog_categories','id'), (SELECT MAX(id) FROM blog_categories));
SELECT setval(pg_get_serial_sequence('blog_tags','id'), (SELECT MAX(id) FROM blog_tags));
SELECT setval(pg_get_serial_sequence('blog_series','id'), (SELECT MAX(id) FROM blog_series));
